### ISSUE TITLE
Missing Dockerfile_sm from falconlite2/sm_build.sh

### ISSUE THREAD

**Issue by aasthavar** [awslabs/extending-the-context-length-of-open-source-llms#6]
I am trying to deploy falconlite2 on Sagemaker - and from the readme understood that need to rebuild the docker image. 
So followed the below steps:
```
git clone https://github.com/awslabs/extending-the-context-length-of-open-source-llms.git falconlite-dev
cd falconlite-dev/falconlite2
sh docker_build.sh
sh sm_build.sh
```
But in the sm_build.sh - Line22, there's a Dockerfile_sm which is missing from code repo. 

Therefore getting this error: **unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/ec2-user/environment/extending-the-context-length-of-open-source-llms/falconlite2/Dockerfile_sm: no such file or directory**

**Comment by aasthavar** [comment]
Also maybe a silly question - why have code to rebuild vllm CUDA kernels in TGI container (filepath - falconlite2/Dockerfile Line: 56-68) ?

**Comment by chenwuperth** [comment]
Hi @aasthavar 
1. to build the SM container, can you please run the [notebook](https://github.com/awslabs/extending-the-context-length-of-open-source-llms/blob/main/falconlite2/sm_deploy.ipynb), which will dynamically generate the `Dockerfile_sm`. Let me know if that can fix your issue.

2. Yes, no worries, good question. the reason we have to rebuild vLLM CUDA kernel is due to this [TGI open issue](https://github.com/huggingface/text-generation-inference/issues/883), which is caused by this [vLLM issue](https://github.com/vllm-project/vllm/issues/905) that has been fixed. But since TGI uses a [custom vLLM implementation](https://github.com/OlivierDehaene/vllm), to apply the fix, we will need to re-build the CUDA kernel for the time being.

**Comment by aasthavar** [comment]
Hi @chenwuperth,

Thank you for your reply ! 

1. Able to deploy model in SM by running the notebook you mentioned. 

2. Makes sense now about re-building vllm CUDA kernel.
